import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 * the puprose of this class is to handle the action events generated by the buttons in the graphical calculator.
 * it implements the ActionListener interface which allows it to listern forand response to button click events.
 * @author (Grace) 
 * @version (2023)
 */
public class ButtonClickListener implements ActionListener
{
    private JTextField textField;
    private double firstNumber;
    private String operator;
    /**
     * Konstruktor für Objekte der Klasse ButtonClickListener
     */
    public ButtonClickListener(JTextField textField)
    {
        super();
        this.textField = textField;
        this.firstNumber = 0;
        this.operator = "";
    }

    /**
     * diese Methode Help to connect the GUI component withthe desired functionalitiy.
     * Also helps to determine what action should be taken(event) when a button is clicked
     * @param event of type ActionEvent
     */
    public void actionPerformed(ActionEvent e){
        String command  = e.getActionCommand();
        if (command.equals("+") || command.equals("-")  || command.equals("/")  || command.equals("*")  )
        {
            // the user have schoosen an operation
            firstNumber = Double.parseDouble(textField.getText() );
            operator = command;
            textField.setText(""); 

        }else if (command.equals("="))
        {
            // the user chooses =
            double secondNumber = Double.parseDouble(textField.getText() );
            double result = 0;

            //______________the operation is executed accordimg to the chosen operator---------
            switch(operator)
            {
                case "+":
                    result = firstNumber + secondNumber;
                    break;
                case "-":
                    result = firstNumber - secondNumber;
                    break;
                case "/":
                    result = firstNumber / secondNumber;
                    break;
                case "*":
                    result = firstNumber * secondNumber;
                    break;
            }

            //_______________the result appears on the text field----------------------
            textField.setText(String.valueOf(result));
        }else if(command.equals(".")) {
            String text = textField.getText();
            if(!text.contains(".")){
                textField.setText(text + ".");
            }
            
            
        }else if (command.equals("C")){
            textField.setText("");
        }else{

            // _____________the user have choosen a number operation------------------
            textField.setText(textField.getText() + command);

        }
    }
}
